# Generated by Django 2.2.7 on 2019-11-22 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=200)),
                ('generic_desc', models.TextField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_name', models.CharField(max_length=200)),
                ('solution_desc', models.TextField(blank=True, max_length=128)),
                ('generic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Generic')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_desc', models.TextField(blank=True, max_length=128)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Solution')),
            ],
        ),
    ]
