# Generated by Django 2.2.7 on 2019-11-22 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='generic',
        ),
    ]
