# Generated by Django 2.2.7 on 2019-11-22 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191122_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='generic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Generic'),
        ),
    ]
