# Generated by Django 2.2.7 on 2019-11-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='POC_SOW',
            field=models.FileField(null=True, upload_to='"POC SOW"/'),
        ),
        migrations.AddField(
            model_name='product',
            name='competitive_information',
            field=models.FileField(null=True, upload_to='"competitive information"/'),
        ),
        migrations.AddField(
            model_name='product',
            name='datasheet',
            field=models.FileField(null=True, upload_to='"data sheet"/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_slide_deck',
            field=models.FileField(null=True, upload_to='"slide deck"/'),
        ),
        migrations.AddField(
            model_name='product',
            name='scoping_document',
            field=models.FileField(null=True, upload_to='"scoping document"/'),
        ),
    ]
