# Generated by Django 2.2.7 on 2019-11-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='POC_SOW',
            field=models.FileField(blank=True, null=True, upload_to='"POC SOW"/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='competitive_information',
            field=models.FileField(blank=True, null=True, upload_to='"competitive information"/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datasheet',
            field=models.FileField(blank=True, null=True, upload_to='"data sheet"/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slide_deck',
            field=models.FileField(blank=True, null=True, upload_to='"slide deck"/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='scoping_document',
            field=models.FileField(blank=True, null=True, upload_to='"scoping document"/'),
        ),
    ]
