# Generated by Django 2.2.7 on 2019-11-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191126_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='POC_SOW',
            field=models.FileField(blank=True, null=True, upload_to='POC_SOW/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='competitive_information',
            field=models.FileField(blank=True, null=True, upload_to='competitiveinfo/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datasheet',
            field=models.FileField(blank=True, null=True, upload_to='datasheet/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slide_deck',
            field=models.FileField(blank=True, null=True, upload_to='slidedeck/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='scoping_document',
            field=models.FileField(blank=True, null=True, upload_to='scopingdoc/'),
        ),
    ]
