# Generated by Django 2.2.7 on 2019-11-26 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20191126_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='generic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Generic'),
        ),
    ]
