# Generated by Django 2.2.7 on 2019-11-26 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_product_generic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='generic',
        ),
    ]
